const constants = {
    ADD_SALAD: "ADD_SALAD",
    REMOVE_SALAD: "REMOVE_SALAD",
    ADD_BACON: "ADD_BACON",
    REMOVE_BACON: "REMOVE_BACON",
    ADD_CHEESE: "ADD_CHEESE",
    REMOVE_CHEESE: "REMOVE_CHEESE",
    ADD_MEAT: "ADD_MEAT",
    REMOVE_MEAT: "REMOVE_MEAT",
    FINISH_ORDER: "FINISH_ORDER"
}

export default constants